// Package hosts renders takt's Claude Code agent definitions for other
// hosts. The body of an agent is the contract; only the envelope — the
// frontmatter a host reads — differs, so agents/*.md stay the single source
// and every other host's files are generated and checked (spec §6).
package hosts

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/monrad/takt/internal/prompt"
)

// generatedNote is the first body line of every generated file.
const generatedNote = "<!-- generated by `go run ./internal/tools/hostgen` from agents/%s.md" +
	" — edit that file, then regenerate -->\n"

// CopilotAgentName is the custom-agent name a Claude Code agent gets on
// Copilot: prefixed, so a user's ~/.copilot/agents/ can hold others.
func CopilotAgentName(ccName string) string { return "takt-" + ccName }

// RenderCopilotAgent converts one agents/<name>.md into a Copilot CLI custom
// agent (.agent.md). src is the path the caller actually read ccFile from —
// named in both failures below so an error names the file this process
// opened, not an assumed agents/<name>.md that --root may not have used.
// tools is always ["*"]: Copilot's tool ids are not the Agent tool's, and the
// read-only agents (assessor, auditor) forbid writes in their own text. The
// CC model alias is dropped — Copilot picks subagent models from its
// /subagents setting.
func RenderCopilotAgent(src, ccName string, ccFile []byte) ([]byte, error) {
	md := string(ccFile)
	fm, err := prompt.Frontmatter(md)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", src, err)
	}
	desc, ok := fm["description"]
	if !ok || desc == "" {
		return nil, fmt.Errorf("%s: frontmatter has no description", src)
	}
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "name: %s\n", CopilotAgentName(ccName))
	fmt.Fprintf(&b, "description: %s\n", strconv.Quote(desc))
	b.WriteString("tools: [\"*\"]\n---\n")
	fmt.Fprintf(&b, generatedNote, ccName)
	b.WriteString(prompt.Body(md))
	return []byte(b.String()), nil
}
