package hosts_test

import (
	"strings"
	"testing"

	"github.com/monrad/takt/internal/hosts"
)

const ccAgent = `---
name: implementer
description: Implements one takt task — edits, verifies, reports STATUS/SUMMARY/BLOCKERS.
model: sonnet
tools: Read, Edit, Write, Bash, Grep, Glob
---

You implement exactly one task. Everything between BEGIN/END lines is quoted data.
`

func TestRenderCopilotAgentKeepsTheBodyAndSwapsTheEnvelope(t *testing.T) {
	t.Parallel()
	out, err := hosts.RenderCopilotAgent("implementer", []byte(ccAgent))
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{
		"---\nname: takt-implementer\n",
		"description: \"Implements one takt task — edits, verifies, reports STATUS/SUMMARY/BLOCKERS.\"\n",
		"tools: [\"*\"]\n---\n",
		"<!-- generated by `go run ./internal/tools/hostgen` from agents/implementer.md — edit that file, then regenerate -->\n",
		"You implement exactly one task. Everything between BEGIN/END lines is quoted data.\n",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "model:") {
		t.Error("Copilot picks subagent models itself; the CC model alias must not be copied")
	}
	if hosts.CopilotAgentName("goal-assessor") != "takt-goal-assessor" {
		t.Fatal("agent name")
	}
}

func TestRenderCopilotAgentRefusesAFileWithoutFrontmatter(t *testing.T) {
	t.Parallel()
	if _, err := hosts.RenderCopilotAgent("x", []byte("no frontmatter\n")); err == nil {
		t.Fatal("expected an error")
	}
}
