package main

import (
	"bytes"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ccAgent is one Claude Code agent definition, the only input hostgen has.
const ccAgent = `---
name: planner
description: Turns the spec into a plan.
model: fable
tools: Read, Grep, Glob, Write
---

You write the plan for one run.
`

// TestRunGeneratesChecksAndSweeps drives hostgen's whole contract against a
// throwaway tree: gen writes the file a source produces, check is then
// silent, and a generated file no source produces any more is reported by
// check and removed by gen. The orphan half is the one hostgen could not see
// before — a content comparison never visits a file it does not render.
func TestRunGeneratesChecksAndSweeps(t *testing.T) {
	t.Parallel()
	root := newRoot(t)
	dst := filepath.Join(root, "hosts", "copilot", "agents", "takt-planner.agent.md")

	if code := run(root, false, io.Discard, io.Discard); code != 0 {
		t.Fatalf("gen exit %d, want 0", code)
	}
	if _, err := os.Stat(dst); err != nil {
		t.Fatal("gen must write the agent the source produces:", err)
	}
	if code := run(root, true, io.Discard, io.Discard); code != 0 {
		t.Fatalf("check exit %d on a freshly generated tree, want 0", code)
	}

	orphan := filepath.Join(root, "hosts", "copilot", "agents", "takt-gone.agent.md")
	if err := os.WriteFile(orphan, []byte("left behind\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if code := run(root, true, io.Discard, io.Discard); code != 1 {
		t.Fatalf("check exit %d with an orphan present, want 1", code)
	}
	if _, err := os.Stat(orphan); err != nil {
		t.Fatal("check must report without writing:", err)
	}
	if code := run(root, false, io.Discard, io.Discard); code != 0 {
		t.Fatalf("gen exit %d, want 0", code)
	}
	if _, err := os.Stat(orphan); !os.IsNotExist(err) {
		t.Fatalf("gen must delete the orphan: %v", err)
	}
	if _, err := os.Stat(dst); err != nil {
		t.Fatal("the sweep must not touch a file a source still produces:", err)
	}
}

// TestRunRefusesATreeWithNoAgents pins hostgen's own error code: exit 1 is
// reserved for a staleness report, so a run that found nothing to render at
// all must not be readable as "one file is stale" either.
func TestRunRefusesATreeWithNoAgents(t *testing.T) {
	t.Parallel()
	if code := run(t.TempDir(), true, io.Discard, io.Discard); code != exitFailure {
		t.Fatalf("exit %d, want %d", code, exitFailure)
	}
}

// TestRunNamesTheRealSourcePathUnderARoot pins #14 end to end: a broken
// agent's failure must name the path this process actually read — resolved
// under a --root other than "." — and never the bare agents/<name>.md the
// two messages used to hardcode. It drives run(), the function that resolves
// the path, and reads the stream the user would have seen, because a message
// that never leaves render() is not the message hostgen prints.
//
// Both of RenderCopilotAgent's failures are covered, since run stops at the
// first broken file: unparseable frontmatter and parseable frontmatter with
// no description were the two that disagreed on style and on the path.
func TestRunNamesTheRealSourcePathUnderARoot(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name    string
		content string
	}{
		{"no frontmatter", "no frontmatter here\n"},
		{"no description", "---\nname: broken\nmodel: sonnet\n---\n\nA body.\n"},
		{"empty description", "---\nname: broken\ndescription:\n---\n\nA body.\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			root := filepath.Join(t.TempDir(), "some-repo")
			if err := os.MkdirAll(filepath.Join(root, "agents"), 0o750); err != nil {
				t.Fatal(err)
			}
			src := filepath.Join(root, "agents", "broken.md")
			if err := os.WriteFile(src, []byte(tc.content), 0o600); err != nil {
				t.Fatal(err)
			}

			var stderr strings.Builder
			if code := run(root, false, io.Discard, &stderr); code != exitFailure {
				t.Fatalf("exit %d, want %d", code, exitFailure)
			}
			got := stderr.String()
			if !strings.Contains(got, src+": ") {
				t.Errorf("hostgen must name the source path %q it read, got: %s", src, got)
			}
			if strings.Contains(got, "hostgen: agents/broken.md") {
				t.Errorf("hostgen must not name a bare agents/broken.md, which assumes --root %q, got: %s", ".", got)
			}
		})
	}
}

// TestRunRegeneratesAHandEditedSkill covers the skill half of the same
// contract the agents get: the file hostgen owns is reported stale when it
// stops matching what commands/takt.md renders to, --check writes nothing,
// and gen puts the generated bytes back. A hand edit is the case that
// matters — the skill was a hand-maintained second copy of the prompt until
// #66, and this is what makes it one again the moment someone edits it.
func TestRunRegeneratesAHandEditedSkill(t *testing.T) {
	t.Parallel()
	root := newRoot(t)
	if code := run(root, false, io.Discard, io.Discard); code != 0 {
		t.Fatalf("gen exit %d, want 0", code)
	}
	skill := filepath.Join(root, "hosts", "copilot", "skills", "takt", "SKILL.md")
	want, err := os.ReadFile(skill)
	if err != nil {
		t.Fatal("gen must write the skill:", err)
	}
	v, verr := manifestVersion(filepath.Join(root, ".claude-plugin", "plugin.json"))
	if verr != nil {
		t.Fatal(verr)
	}
	if !strings.Contains(string(want), "takt version --expect "+v+"`") {
		t.Errorf("the generated skill must pin the seeded manifest's version %q, got:\n%s", v, want)
	}
	if code := run(root, true, io.Discard, io.Discard); code != 0 {
		t.Fatalf("check exit %d on a freshly generated tree, want 0", code)
	}

	if werr := os.WriteFile(skill, []byte("# hand-edited\n"), 0o600); werr != nil {
		t.Fatal(werr)
	}
	var stderr strings.Builder
	if code := run(root, true, io.Discard, &stderr); code != 1 {
		t.Fatalf("check exit %d with a hand-edited skill, want 1", code)
	}
	if !strings.Contains(stderr.String(), "stale: "+skill) {
		t.Errorf("check must report %s as stale, got: %s", skill, stderr.String())
	}
	if cur, rerr := os.ReadFile(skill); rerr != nil || string(cur) != "# hand-edited\n" {
		t.Errorf("check must report without writing: %q, %v", cur, rerr)
	}
	if code := run(root, false, io.Discard, io.Discard); code != 0 {
		t.Fatalf("gen exit %d, want 0", code)
	}
	if got, rerr := os.ReadFile(skill); rerr != nil || !bytes.Equal(got, want) {
		t.Errorf("gen must rewrite the hand-edited skill: %v", rerr)
	}
}

// TestRunRefusesARootMissingASkillSource pins both halves of the skill
// generator's input contract, because both are the same mistake seen from
// different sides: a --root that is not a takt checkout. Neither file may be
// treated as optional — skipping the render when an input is absent is
// indistinguishable, at the exit code, from "the skill is up to date", which
// is exactly the drift this generator exists to end. The messages are read
// off run()'s stderr rather than the process's, because a message that never
// leaves a helper is not the message hostgen prints.
func TestRunRefusesARootMissingASkillSource(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name    string
		missing string
	}{
		{"no prompt", filepath.Join("commands", "takt.md")},
		{"no manifest", filepath.Join(".claude-plugin", "plugin.json")},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			root := newRoot(t)
			if err := os.Remove(filepath.Join(root, tc.missing)); err != nil {
				t.Fatal(err)
			}
			var stderr strings.Builder
			if code := run(root, false, io.Discard, &stderr); code != exitFailure {
				t.Fatalf("exit %d, want %d", code, exitFailure)
			}
			if got := stderr.String(); !strings.Contains(got, filepath.Join(root, tc.missing)) {
				t.Errorf("hostgen must name the missing %s under the root it was given, got: %s", tc.missing, got)
			}
		})
	}
}

// newRoot builds a throwaway repository root hostgen accepts: one agent
// source, plus the two files the skill is rendered from.
func newRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "agents"), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "agents", "planner.md"), []byte(ccAgent), 0o600); err != nil {
		t.Fatal(err)
	}
	for _, rel := range []string{
		filepath.Join("commands", "takt.md"),
		filepath.Join(".claude-plugin", "plugin.json"),
	} {
		seed(t, root, rel)
	}
	return root
}

// seed copies the repository's own file at rel — read through ../../../, the
// way back up from this package — to the same relative path under root. The
// skill is rendered from the real prompt and the real manifest rather than
// from a fixture: the profile in internal/hosts matches commands/takt.md as
// it is committed, so a fixture would either duplicate that file or make
// these tests pass against a document the generator cannot render.
func seed(t *testing.T, root, rel string) {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("..", "..", "..", rel))
	if err != nil {
		t.Fatal(err)
	}
	dst := filepath.Join(root, rel)
	if err = os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile(dst, b, 0o600); err != nil {
		t.Fatal(err)
	}
}
